name: Docker Image Publish

on:
    push:
        branches: [ "main" ]
        tags: [ "v*.*.*" ]
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout domain models repository
              uses: actions/checkout@v3
              with:
                repository: ScarletPigs/PigletDomainModels
                path: PigletDomainModels

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha,mode=max

            - name: Tell Watchtower to update the image
              shell: bash
              run: |
                curl -H "Authorization: Bearer ${{ secrets.UPDATE_TOKEN }}" ${{ secrets.WATCHTOWER_URL }}/v1/update
